[package]
name = "personal-website"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
dotenv = "0.15.0"
maud = "0.27.0"
rusqlite = "0.36.0"
serde = "1.0.219"
serde_json = "1.0.140"
tiny_http = "0.12.0"
ureq = "3.0.12"
